// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObwn0LH9znhc3E-CCtdWg5WiPm11Zkjw',
    appId: '1:35328388612:web:90b20061d95a1cde378f51',
    messagingSenderId: '35328388612',
    projectId: 'scancook-e0ee8',
    authDomain: 'scancook-e0ee8.firebaseapp.com',
    storageBucket: 'scancook-e0ee8.firebasestorage.app',
    measurementId: 'G-P8KK1PLJP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp3RmLS_il-cZHNrvpdYNT-olq70PZodE',
    appId: '1:35328388612:android:4b720bca698de546378f51',
    messagingSenderId: '35328388612',
    projectId: 'scancook-e0ee8',
    storageBucket: 'scancook-e0ee8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqgumqdb9FlrNrrlKvcGV3igQyI4vZ-s8',
    appId: '1:35328388612:ios:a886f84a8b6ce5e4378f51',
    messagingSenderId: '35328388612',
    projectId: 'scancook-e0ee8',
    storageBucket: 'scancook-e0ee8.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqgumqdb9FlrNrrlKvcGV3igQyI4vZ-s8',
    appId: '1:35328388612:ios:a886f84a8b6ce5e4378f51',
    messagingSenderId: '35328388612',
    projectId: 'scancook-e0ee8',
    storageBucket: 'scancook-e0ee8.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBObwn0LH9znhc3E-CCtdWg5WiPm11Zkjw',
    appId: '1:35328388612:web:ff3212104035f74c378f51',
    messagingSenderId: '35328388612',
    projectId: 'scancook-e0ee8',
    authDomain: 'scancook-e0ee8.firebaseapp.com',
    storageBucket: 'scancook-e0ee8.firebasestorage.app',
    measurementId: 'G-JSD7NBMB77',
  );
}
